#!/bin/bash
LOG_FILE="${TRIM_DATA_SHARE_PATHS%%:*}/info.log"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

#=== 重置配置文件 ===
CONFIG_TEMPLATE="${TRIM_APPDEST}/template/BitComet.tpl"
CONFIG_FILE="${TRIM_DATA_SHARE_PATHS%%:*}/data/BitComet.xml"

sed \
  -e "s|\${BT_USERNAME}|$bt_username|g" \
  -e "s|\${BT_PASSWORD}|$bt_password|g" \
  -e "s|\${BT_PORT}|$bt_port|g" \
  "$CONFIG_TEMPLATE" > "$CONFIG_FILE"
log_msg "配置已成功重置"

exit 0